class CountLimitData {

	constructor(settings) {
		// Set the parameters from the settings file.
		const { MAXIMUM_SEARCH_PROCESSES_COUNT, MAXIMUM_SEARCH_ENGINE_PAGES_PER_PROCESS_COUNT, MAXIMUM_SEARCH_KEY_CHARACTERS_COUNT,
			MINIMUM_SEARCH_KEY_CHARACTERS_COUNT, MAXIMUM_RETRIES_GENERATE_SEARCH_KEY_COUNT,
			MAXIMUM_DISPLAY_SEARCH_KEY_CHARACTERS_COUNT, MILLISECONDS_INTERVAL_COUNT, MILLISECONDS_DELAY_BETWEEN_PROCESS_COUNT,
			MILLISECONDS_DELAY_BETWEEN_SEARCH_PAGES_COUNT, MILLISECONDS_DELAY_BETWEEN_CRAWL_PAGES_COUNT, MILLISECONDS_DELAY_MONGO_DATABASE_SYNC_COUNT,
			MILLISECONDS_TIMEOUT_SOURCE_REQUEST_COUNT, MAXIMUM_CONSOLE_LINE_CHARACTERS, MAXIMUM_TRENDING_SAVE_COUNT,
			MAXIMUM_SAVE_EMAIL_ADDRESS_RETRIES_COUNT, MAXIMUM_ERROR_PAGE_IN_A_ROW_COUNT, MAXIMUM_UNSAVE_EMAIL_ADDRESSES_COUNT,
			MAXIMUM_UNIQUE_DOMAIN_COUNT, MAXIMUM_URL_VALIDATION_COUNT, MILLISECONDS_TIMEOUT_URL_VALIDATION
		} = settings;
		this.maximumSearchProcessesCount = MAXIMUM_SEARCH_PROCESSES_COUNT;
		this.maximumSearchEnginePagesPerProcessCount = MAXIMUM_SEARCH_ENGINE_PAGES_PER_PROCESS_COUNT;
		this.maximumSearchKeyCharactersCount = MAXIMUM_SEARCH_KEY_CHARACTERS_COUNT;
		this.minimumSearchKeyCharactersCount = MINIMUM_SEARCH_KEY_CHARACTERS_COUNT;
		this.maximumRetriesGenerateSearchKeyCount = MAXIMUM_RETRIES_GENERATE_SEARCH_KEY_COUNT;
		this.maximumDisplaySearchKeyCharactersCount = MAXIMUM_DISPLAY_SEARCH_KEY_CHARACTERS_COUNT;
		this.millisecondsIntervalCount = MILLISECONDS_INTERVAL_COUNT;
		this.millisecondsDelayBetweenProcessCount = MILLISECONDS_DELAY_BETWEEN_PROCESS_COUNT;
		this.millisecondsDelayBetweenSearchPagesCount = MILLISECONDS_DELAY_BETWEEN_SEARCH_PAGES_COUNT;
		this.millisecondsDelayBetweenCrawlPagesCount = MILLISECONDS_DELAY_BETWEEN_CRAWL_PAGES_COUNT;
		this.millisecondsDelayMongoDatabaseSyncCount = MILLISECONDS_DELAY_MONGO_DATABASE_SYNC_COUNT;
		this.millisecondsTimeoutSourceRequestCount = MILLISECONDS_TIMEOUT_SOURCE_REQUEST_COUNT;
		this.maximumConsoleLineCharacters = MAXIMUM_CONSOLE_LINE_CHARACTERS;
		this.maximumTrendingSaveCount = MAXIMUM_TRENDING_SAVE_COUNT;
		this.maximumSaveEmailAddressesRetriesCount = MAXIMUM_SAVE_EMAIL_ADDRESS_RETRIES_COUNT;
		this.maximumErrorPageInARowCount = MAXIMUM_ERROR_PAGE_IN_A_ROW_COUNT;
		this.maximumUnsaveEmailAddressesCount = MAXIMUM_UNSAVE_EMAIL_ADDRESSES_COUNT;
		this.maximumUniqueDomainCount = MAXIMUM_UNIQUE_DOMAIN_COUNT;
		this.maximumURLValidationCount = MAXIMUM_URL_VALIDATION_COUNT;
		this.millisecondsTimeoutURLValidation = MILLISECONDS_TIMEOUT_URL_VALIDATION;
	}
}

module.exports = CountLimitData;