class TestData {

	constructor(settings) {
		// Set the parameters from the settings file.
		const { MINIMUM_CREATE_RANDOM_EMAIL_ADDRESSES_COUNT, MAXIMUM_CREATE_RANDOM_EMAIL_ADDRESSES_COUNT,
			MINIMUM_SPECIAL_CHARACTERS_TYPOS_EMAIL_ADDRESSES_COUNT, MAXIMUM_SPECIAL_CHARACTERS_TYPOS_EMAIL_ADDRESSES_COUNT,
			MINIMUM_SPECIAL_CHARACTERS_COUNT, MAXIMUM_SPECIAL_CHARACTERS_COUNT, MAXIMUM_LOCAL_TEST_SIMPLE_CHARACTERS_COUNT,
			MAXIMUM_DOMAIN_TEST_SIMPLE_CHARACTERS_COUNT, MINIMUM_REPLACE_RANDOM_POSITIONS_COUNT, MAXIMUM_REPLACE_RANDOM_POSITIONS_COUNT,
			MINIMUM_TEST_RANDOM_WORDS_COUNT, MAXIMUM_TEST_RANDOM_WORDS_COUNT, MINIMUM_RANDOM_PART_CHARACTERS_COUNT
		} = settings;
		this.minimumCreateRandomEmailAddressesCount = MINIMUM_CREATE_RANDOM_EMAIL_ADDRESSES_COUNT;
		this.maximumCreateRandomEmailAddressesCount = MAXIMUM_CREATE_RANDOM_EMAIL_ADDRESSES_COUNT;
		this.minimumSpecialCharactersTyposEmailAddressesCount = MINIMUM_SPECIAL_CHARACTERS_TYPOS_EMAIL_ADDRESSES_COUNT;
		this.maximumSpecialCharactersTyposEmailAddressesCount = MAXIMUM_SPECIAL_CHARACTERS_TYPOS_EMAIL_ADDRESSES_COUNT;
		this.minimumSpecialCharactersCount = MINIMUM_SPECIAL_CHARACTERS_COUNT;
		this.maximumSpecialCharactersCount = MAXIMUM_SPECIAL_CHARACTERS_COUNT;
		this.maximumLocalTestSimpleCharactersCount = MAXIMUM_LOCAL_TEST_SIMPLE_CHARACTERS_COUNT;
		this.maximumDomainTestSimpleCharactersCount = MAXIMUM_DOMAIN_TEST_SIMPLE_CHARACTERS_COUNT;
		this.minimumReplaceRandomPositionsCount = MINIMUM_REPLACE_RANDOM_POSITIONS_COUNT;
		this.maximumReplaceRandomPositionsCount = MAXIMUM_REPLACE_RANDOM_POSITIONS_COUNT;
		this.minimumTestRandomWordsCount = MINIMUM_TEST_RANDOM_WORDS_COUNT;
		this.maximumTestRandomWordsCount = MAXIMUM_TEST_RANDOM_WORDS_COUNT;
		this.minimumRandomPartCharactersCount = MINIMUM_RANDOM_PART_CHARACTERS_COUNT;
	}
}

module.exports = TestData;